#!/usr/bin/env python3

import sys
import reader

# read command line args in this format
# coherence “protocol” “input_file” “cache_size” “associativity” “block_size”
if len(sys.argv) != 6:
    print("Wrong number of arguments, usage:")
    print("    coherence 'protocol' 'input_file' 'cache_size' 'associativity' 'block_size'")
    sys.exit(2)

_, protocol, input_file, cache_size, associativity, block_size = sys.argv

print(input_file)

reader.read_files(input_file)
